version: '3'

services:
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - '3000:3000'
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
